version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm build 
  artifacts:
    files:
      - '**/*'
    discard-paths: yes
    base-directory: 'assets/public/simple-reactjs-app'
